"""v0.2 collector raw_payload as JSON

Revision ID: 37f788d24311
Revises: 937a152aeca9
Create Date: 2026-08-31 15:46:42.668103

"""
import sqlalchemy as sa

from alembic import op

revision = '37f788d24311'
down_revision = '937a152aeca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.alter_column('raw_payload_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.alter_column('raw_payload_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
