"""phase 2.1 domain model hardening

Revision ID: 4a48e7786118
Revises: e2bcd6b51463
Create Date: 2026-08-30 22:08:20.689420

"""
from alembic import op
import sqlalchemy as sa


revision = '4a48e7786118'
down_revision = 'e2bcd6b51463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_job_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('establishment_status', sa.String(length=32), nullable=False),
    sa.Column('tenure_status', sa.String(length=32), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('funding_source', sa.String(length=32), nullable=False),
    sa.Column('contract_years', sa.Integer(), nullable=True),
    sa.Column('first_contract_period', sa.String(length=128), nullable=True),
    sa.Column('is_up_or_out', sa.Boolean(), nullable=True),
    sa.Column('midterm_review', sa.Text(), nullable=True),
    sa.Column('final_review', sa.Text(), nullable=True),
    sa.Column('publication_requirements', sa.Text(), nullable=True),
    sa.Column('grant_requirements', sa.Text(), nullable=True),
    sa.Column('teaching_requirements', sa.Text(), nullable=True),
    sa.Column('admin_requirements', sa.Text(), nullable=True),
    sa.Column('current_title', sa.String(length=128), nullable=True),
    sa.Column('promotion_path', sa.Text(), nullable=True),
    sa.Column('independent_pi', sa.Boolean(), nullable=True),
    sa.Column('lab_space', sa.Text(), nullable=True),
    sa.Column('startup_funding', sa.Text(), nullable=True),
    sa.Column('startup_funding_terms', sa.Text(), nullable=True),
    sa.Column('can_supervise_master', sa.Boolean(), nullable=True),
    sa.Column('can_supervise_phd', sa.Boolean(), nullable=True),
    sa.Column('master_quota', sa.String(length=128), nullable=True),
    sa.Column('phd_quota', sa.String(length=128), nullable=True),
    sa.Column('fixed_income', sa.Text(), nullable=True),
    sa.Column('performance_income', sa.Text(), nullable=True),
    sa.Column('housing_settlement', sa.Text(), nullable=True),
    sa.Column('housing_subsidy', sa.Text(), nullable=True),
    sa.Column('talent_housing', sa.Text(), nullable=True),
    sa.Column('regional_talent_subsidy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_job_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_job_details_job_id'), ['job_id'], unique=True)

    op.create_table('evaluation_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['job_evaluations.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'evidence_id', name='uq_evaluation_evidence')
    )
    with op.batch_alter_table('evaluation_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_evidence_evaluation_id'), ['evaluation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_evidence_evidence_id'), ['evidence_id'], unique=False)

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_author', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('is_firsthand', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('independence_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('repost_of_evidence_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stance', sa.String(length=16), nullable=False,
                                      server_default=sa.text("'unknown'")))
        batch_op.add_column(sa.Column('scope_level', sa.String(length=16), nullable=False,
                                      server_default=sa.text("'unknown'")))
        batch_op.add_column(sa.Column('scope_name', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_evidence_independence_key'), ['independence_key'], unique=False)
        batch_op.create_foreign_key('fk_evidence_repost_of_evidence_id', 'evidence',
                                    ['repost_of_evidence_id'], ['id'])

    with op.batch_alter_table('job_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_coverage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_items_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('profile_snapshot_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('profile_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('scoring_config_snapshot_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scoring_config_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('region_config_snapshot_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('region_config_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('input_snapshot_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('salary_period', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('guaranteed_salary_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('guaranteed_salary_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('variable_salary_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('variable_salary_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advertised_total_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advertised_total_max', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('advertised_total_max')
        batch_op.drop_column('advertised_total_min')
        batch_op.drop_column('variable_salary_max')
        batch_op.drop_column('variable_salary_min')
        batch_op.drop_column('guaranteed_salary_max')
        batch_op.drop_column('guaranteed_salary_min')
        batch_op.drop_column('salary_period')
        batch_op.drop_column('salary_currency')

    with op.batch_alter_table('job_evaluations', schema=None) as batch_op:
        batch_op.drop_column('input_snapshot_json')
        batch_op.drop_column('region_config_hash')
        batch_op.drop_column('region_config_snapshot_json')
        batch_op.drop_column('scoring_config_hash')
        batch_op.drop_column('scoring_config_snapshot_json')
        batch_op.drop_column('profile_hash')
        batch_op.drop_column('profile_snapshot_json')
        batch_op.drop_column('provider')
        batch_op.drop_column('risk_items_json')
        batch_op.drop_column('score_coverage')

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_repost_of_evidence_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_evidence_independence_key'))
        batch_op.drop_column('scope_name')
        batch_op.drop_column('scope_level')
        batch_op.drop_column('stance')
        batch_op.drop_column('repost_of_evidence_id')
        batch_op.drop_column('independence_key')
        batch_op.drop_column('is_firsthand')
        batch_op.drop_column('source_author')

    with op.batch_alter_table('evaluation_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_evidence_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_evidence_evaluation_id'))

    op.drop_table('evaluation_evidence')
    with op.batch_alter_table('academic_job_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_job_details_job_id'))

    op.drop_table('academic_job_details')
    # ### end Alembic commands ###
