"""v0.2.2 collector recency skipped count

Revision ID: 87c3300ba3ba
Revises: 37f788d24311
Create Date: 2026-08-31 17:34:38.759257

"""
import sqlalchemy as sa

from alembic import op

revision = '87c3300ba3ba'
down_revision = '37f788d24311'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default：已有运行历史的表不能加无默认值的 NOT NULL 列（SQLite batch 重建会失败）
    with op.batch_alter_table('collector_run_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recency_skipped_count', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('collector_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recency_skipped_count', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_runs', schema=None) as batch_op:
        batch_op.drop_column('recency_skipped_count')

    with op.batch_alter_table('collector_run_items', schema=None) as batch_op:
        batch_op.drop_column('recency_skipped_count')

    # ### end Alembic commands ###
