"""v0.2 collector: runs, run items, discovered jobs

Revision ID: 937a152aeca9
Revises: d281b97059b5
Create Date: 2026-08-31 15:40:31.027981

"""
import sqlalchemy as sa

from alembic import op

revision = '937a152aeca9'
down_revision = 'd281b97059b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('completed_source_count', sa.Integer(), nullable=False),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('possible_duplicate_count', sa.Integer(), nullable=False),
    sa.Column('filtered_count', sa.Integer(), nullable=False),
    sa.Column('failed_source_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovered_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_job_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('title_raw', sa.String(length=512), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('published_at_raw', sa.String(length=64), nullable=True),
    sa.Column('organization_hint', sa.String(length=256), nullable=True),
    sa.Column('location_hint', sa.String(length=128), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_run_id', sa.Integer(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('possible_duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_reason', sa.String(length=256), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('imported_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['possible_duplicate_of_id'], ['discovered_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_job_id', name='uq_discovered_source_job')
    )
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_jobs_canonical_url'), ['canonical_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_discovered_jobs_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_discovered_jobs_possible_duplicate_of_id'),
            ['possible_duplicate_of_id'], unique=False,
        )
        batch_op.create_index(batch_op.f('ix_discovered_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_jobs_status'), ['status'], unique=False)

    op.create_table('collector_run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('possible_duplicate_count', sa.Integer(), nullable=False),
    sa.Column('filtered_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['collector_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collector_run_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collector_run_items_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_run_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collector_run_items_run_id'))

    op.drop_table('collector_run_items')
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_possible_duplicate_of_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_canonical_url'))

    op.drop_table('discovered_jobs')
    op.drop_table('collector_runs')
    # ### end Alembic commands ###
