"""v0.3 sector on discovered jobs and run items

Revision ID: 9834a5845c71
Revises: 87c3300ba3ba
Create Date: 2026-09-01 10:36:17.070505

"""
import sqlalchemy as sa

from alembic import op

revision = '9834a5845c71'
down_revision = '87c3300ba3ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default='other'：已有行（历史发现/运行记录）迁移为 other，不产生 NULL。
    # 历史记录的来源分类在发现时冻结 —— 不根据当前 sources.yaml 动态反查。
    with op.batch_alter_table('collector_run_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=24), nullable=False,
                                      server_default='other'))

    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=24), nullable=False,
                                      server_default='other'))
        batch_op.create_index(batch_op.f('ix_discovered_jobs_sector'), ['sector'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_sector'))
        batch_op.drop_column('sector')

    with op.batch_alter_table('collector_run_items', schema=None) as batch_op:
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
