"""phase 3.1 job import audit

Revision ID: d281b97059b5
Revises: 4a48e7786118
Create Date: 2026-08-30 23:32:55.812888

"""
from alembic import op
import sqlalchemy as sa


revision = 'd281b97059b5'
down_revision = '4a48e7786118'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_import_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_method', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('extraction_json', sa.JSON(), nullable=True),
    sa.Column('confirmed_payload_json', sa.JSON(), nullable=True),
    sa.Column('source_text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_import_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_import_records_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_import_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_import_records_job_id'))

    op.drop_table('job_import_records')
    # ### end Alembic commands ###
