"""initial schema

Revision ID: e2bcd6b51463
Revises: 
Create Date: 2026-08-30 21:29:48.734660

"""
import sqlalchemy as sa

from alembic import op

revision = 'e2bcd6b51463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('organization_type', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('official_url', sa.String(length=1024), nullable=True),
    sa.Column('career_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_job_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('job_category', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_clean', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('position_nature', sa.String(length=32), nullable=False),
    sa.Column('salary_text', sa.String(length=256), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('degree_requirement', sa.String(length=128), nullable=True),
    sa.Column('experience_requirement', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_priority', sa.Integer(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resume_version', sa.String(length=64), nullable=True),
    sa.Column('cover_letter_version', sa.String(length=64), nullable=True),
    sa.Column('contact', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_action', sa.String(length=256), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=True)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_title', sa.String(length=256), nullable=True),
    sa.Column('evidence_level', sa.String(length=1), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_organization_id'), ['organization_id'], unique=False)

    op.create_table('job_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('career_stability_score', sa.Float(), nullable=True),
    sa.Column('research_resources_score', sa.Float(), nullable=True),
    sa.Column('region_score', sa.Float(), nullable=True),
    sa.Column('compensation_score', sa.Float(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('workload_score', sa.Float(), nullable=True),
    sa.Column('long_term_score', sa.Float(), nullable=True),
    sa.Column('recommendation_level', sa.String(length=2), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('confidence_level', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths_json', sa.JSON(), nullable=True),
    sa.Column('weaknesses_json', sa.JSON(), nullable=True),
    sa.Column('risks_json', sa.JSON(), nullable=True),
    sa.Column('unknowns_json', sa.JSON(), nullable=True),
    sa.Column('questions_json', sa.JSON(), nullable=True),
    sa.Column('hard_filters_json', sa.JSON(), nullable=True),
    sa.Column('evaluation_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_evaluations_job_id'), ['job_id'], unique=False)

    op.create_table('job_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_text', sa.String(length=256), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_versions_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_versions_job_id'))

    op.drop_table('job_versions')
    with op.batch_alter_table('job_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_evaluations_job_id'))

    op.drop_table('job_evaluations')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_organization_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_job_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_jobs_city'))

    op.drop_table('jobs')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
